### ISSUE TITLE
Example doesn't seem to work with Chrome Canary Version 104.0.5086.0 (Apple silicon)

### ISSUE THREAD

**Issue by monfera** [morzel85/webgpu-wgsl-hello-triangle#1]
The WebGPU flag is enabled, and I don't get the alert that says it isn't.

I haven't tested if it works for other platforms, just wanted to mention

<img width="1799" alt="image" src="https://user-images.githubusercontent.com/1548516/170768952-cce6ed37-4020-4f09-8322-eff0e98b509b.png">

**Comment by morzel85** [comment]
It has been a while since I last looked at WebGPU and a lot has changed... I'm not tracking this topic anymore and I'll archive the repo. 

I see that you have your own version: https://github.com/monfera/minimal-webgpu-triangle, so I'll put that link to the README.
